package ar.edu.utn.frba.dds.Models.Domain.Heladera;

public enum Estado {
    ACTIVA,
    INACTIVA_INCIDENTE_ALERTA_TEMPERATURA,
    INACTIVA_INCIDENTE_ALERTA_FRAUDE,
    INACTIVA_INCIDENTE_ALERTA_FALLA_CONEXION,
    INACTIVA_INCIDENTE_FALLA_TECNICA,
    INACTIVA_INCIDENTE_ALERTA_MOVIMIENTO,
}
