@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "ar.edu.utn.frba.dds.Validador.Session#register()",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "ar.edu.utn.frba.dds.Validador.Session",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_100278 { 
   	label=edu
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1878955145 { 
   	label=utn
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1020759165 { 
   	label=PasswordGenerator
	labeljust=l
	fillcolor=white
	style=filled
   
   PasswordGenerator1930737625XXXgenerateRandomPassword104431[
	label="+ generateRandomPassword()"
	style=filled
	fillcolor=white
	tooltip="PasswordGenerator

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1337061873 { 
   	label=Main
	labeljust=l
	fillcolor=white
	style=filled
   
   Main539222008XXXmain1859653459[
	label="+ main()"
	style=filled
	fillcolor=white
	tooltip="Main

null"
	fontcolor=darkgreen
];

Main539222008XXXpaginaInicio0[
	label="+ paginaInicio()"
	style=filled
	fillcolor=white
	tooltip="Main

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1928034871 { 
   	label=PasswordValidation
	labeljust=l
	fillcolor=white
	style=filled
   
   PasswordValidation1930737625XXXesPasswordIgualAUsuario2013066710[
	label="+ esPasswordIgualAUsuario()"
	style=filled
	fillcolor=white
	tooltip="PasswordValidation

null"
	fontcolor=darkgreen
];

PasswordValidation1930737625XXXvalidarPassword2013066710[
	label="+ validarPassword()"
	style=filled
	fillcolor=white
	tooltip="PasswordValidation

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_2080358090 { 
   	label=Mensajes
	labeljust=l
	fillcolor=white
	style=filled
   
   Mensajes539222008XXXgetMsgIntentosFallidos672261858[
	label="+ getMsgIntentosFallidos()"
	style=filled
	fillcolor=white
	tooltip="Mensajes

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_270504576 { 
   	label=Session
	labeljust=l
	fillcolor=white
	style=filled
   
   Session539222008XXXregister0[
	label="+ register()"
	style=filled
	fillcolor=white
	tooltip="Session

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_325827142 { 
   	label=ManejoArchivo
	labeljust=l
	fillcolor=white
	style=filled
   
   ManejoArchivo539222008XXXcheckUser1808118735[
	label="+ checkUser()"
	style=filled
	fillcolor=white
	tooltip="ManejoArchivo

null"
	fontcolor=darkgreen
];

ManejoArchivo539222008XXXsaveUserAndPass2013066710[
	label="+ saveUserAndPass()"
	style=filled
	fillcolor=white
	tooltip="ManejoArchivo

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_728985288 { 
   	label=Register
	labeljust=l
	fillcolor=white
	style=filled
   
   Register1930737625XXXregister0[
	label="+ register()"
	style=filled
	fillcolor=white
	tooltip="Register

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_864088818 { 
   	label=Hasheo
	labeljust=l
	fillcolor=white
	style=filled
   
   Hasheo539222008XXXhashearPass1808118735[
	label="+ hashearPass()"
	style=filled
	fillcolor=white
	tooltip="Hasheo

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
Main539222008XXXmain1859653459 -> Main539222008XXXpaginaInicio0;
Main539222008XXXpaginaInicio0 -> Main539222008XXXpaginaInicio0;
Main539222008XXXpaginaInicio0 -> Session539222008XXXregister0;
PasswordValidation1930737625XXXvalidarPassword2013066710 -> PasswordValidation1930737625XXXesPasswordIgualAUsuario2013066710;
Register1930737625XXXregister0 -> Hasheo539222008XXXhashearPass1808118735;
Register1930737625XXXregister0 -> ManejoArchivo539222008XXXcheckUser1808118735;
Register1930737625XXXregister0 -> ManejoArchivo539222008XXXsaveUserAndPass2013066710;
Register1930737625XXXregister0 -> Mensajes539222008XXXgetMsgIntentosFallidos672261858;
Register1930737625XXXregister0 -> PasswordGenerator1930737625XXXgenerateRandomPassword104431;
Register1930737625XXXregister0 -> PasswordValidation1930737625XXXesPasswordIgualAUsuario2013066710;
Register1930737625XXXregister0 -> PasswordValidation1930737625XXXvalidarPassword2013066710;
Session539222008XXXregister0 -> Register1930737625XXXregister0;
    
}
@enduml